server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:mysql://${RDB_HOST}:${RDB_PORT}/${RDB_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  jackson:
    time-zone: Asia/Seoul
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_SCHEMA}?retryWrites=true&w=majority&appName=root

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-time: 1209600000 # 14 day = 14 * 1000 * 60 * 60 * 24
  refresh-token-expiration-time: 15552000000 # 180 day = 180 * 1000 * 60 * 60 * 24 *14

slack:
  secret: ${SLACK_SECRET} #token

apple:
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  team-id: ${APPLE_TEAM_ID}
  private-key: ${APPLE_PRIVATE_KEY}